### ISSUE TITLE
How to  visualize multi camera tracks?

### ISSUE THREAD

**Issue by SaraXuBing** [koehlp/wda_tracker#2]
Hi Philipp,

Thank you very much for the excellent network.

I have some problems with visualizing multi-camera tracks. I run a file in utilities which named "draw_multi_camera_tracks.py"  after the command “python run_multi_cam_clustering.py   --config configs/clustering_configs/mta_es_abd_non_clean.py”

But there is an error that can't find the file which path is "work_dirs/evaluation/multi_cam_trackwise_evaluation/eval_results.csv"      
Below is the error message:

Traceback (most recent call last):
  File "draw_multi_camera_tracks.py", line 346, in <module>
    trv.run_visualization()
  File "draw_multi_camera_tracks.py", line 284, in run_visualization
    track_evaluation_results = self.read_track_evaluation_results()
  File "draw_multi_camera_tracks.py", line 74, in read_track_evaluation_results
    track_evaluation_results = pd.read_csv(self.track_evaluation_results_path)
  File "/home/xb/anaconda3/envs/wda/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/xb/anaconda3/envs/wda/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/xb/anaconda3/envs/wda/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/xb/anaconda3/envs/wda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/xb/anaconda3/envs/wda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /home/xb/wda_tracker/wda_tracker-master/work_dirs/evaluation/multi_cam_trackwise_evaluation/eval_results.csv does not exist: '/home/xb/wda_tracker/wda_tracker-master/work_dirs/evaluation/multi_cam_trackwise_evaluation/eval_results.csv'

Should I run some file to create "eval_results.csv" before running "draw_multi_camera_tracks.py"?
Or did I run the wrong file to visualize multi-camera tracks? 

Look forward to your reply, thank you!

**Comment by koehlp** [comment]
Hi SaraXuBing,
I used this script to draw generated multi camera tracks and ground truth multi camera tracks that have the minimal matching error into one image. This means the IDTPs and IDFPs were minimal for each pair in all result tracks and ground truth tracks.
I created this assignment using the following file:
https://github.com/koehlp/wda_tracker/blob/master/evaluation/multicam_trackwise_evaluation.py

Unfortunately this script is still based on single images. Due to the big size of the dataset I converted the images into videos.
So it would be required to adjust this script to be able to draw these tracks into images.

Best regards,

Philipp

**Comment by SaraXuBing** [comment]
Hi Philipp


Thank you very much for your reply.&nbsp;
I will try to run this script, but now I have another trouble that I am studing mtmc tracking, but I can't download Dukemtmc video dataset which size is 160G.&nbsp;
Do you have it? If you have it, can you share it to me? This dataset is very important for me.


I am looking forward to your next letter soon.



Sara
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "koehlp/wda_tracker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 凌晨3:13
收件人:&nbsp;"koehlp/wda_tracker"<wda_tracker@noreply.github.com&gt;;
抄送:&nbsp;"徐冰"<1097465337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [koehlp/wda_tracker] How to  visualize multi camera tracks? (#2)





 
Hi SaraXuBing,
 I used this script to draw generated multi camera tracks and ground truth multi camera tracks that have the minimal matching error into one image. This means the IDTPs and IDFPs were minimal for each pair in all result tracks and ground truth tracks.
 I created this assignment using the following file:
 https://github.com/koehlp/wda_tracker/blob/master/evaluation/multicam_trackwise_evaluation.py
 
Unfortunately this script is still based on single images. Due to the big size of the dataset I converted the images into videos.
 So it would be required to adjust this script to be able to draw these tracks into images.
 
Best regards,
 
Philipp

**Comment by koehlp** [comment]
Hey SaraXuBing,

The DukeMTMC dataset has been removed due to privacy issues (https://www.dukechronicle.com/article/2019/06/duke-university-facial-recognition-data-set-study-surveillance-video-students-china-uyghur). This was a reason why we created the MTA dataset. You cannot publish research based on the DukeMTMC I guess.

Best regards,

Philipp

**Comment by SaraXuBing** [comment]
Hi Philipp


First of all, thanks for your reply.
The MAT dataset is an amazing job, and I'll do my research on it. I hope we can keep in touch to communicate with MTMC tracking.&nbsp;


Yours sincerely


Sara


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "koehlp/wda_tracker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 凌晨0:11
收件人:&nbsp;"koehlp/wda_tracker"<wda_tracker@noreply.github.com&gt;;
抄送:&nbsp;"徐冰"<1097465337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [koehlp/wda_tracker] How to  visualize multi camera tracks? (#2)





 
Hey SaraXuBing,
 
The DukeMTMC dataset has been removed due to privacy issues (https://www.dukechronicle.com/article/2019/06/duke-university-facial-recognition-data-set-study-surveillance-video-students-china-uyghur). This was a reason why we created the MTA dataset. You cannot publish research based on the DukeMTMC I guess.
 
Best regards,
 
Philipp

**Comment by HulkMaker** [comment]
> Hi Philipp First of all, thanks for your reply. The MAT dataset is an amazing job, and I'll do my research on it. I hope we can keep in touch to communicate with MTMC tracking.&nbsp; Yours sincerely Sara
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "koehlp/wda_tracker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月18日(星期六) 凌晨0:11 收件人:&nbsp;"koehlp/wda_tracker"<wda_tracker@noreply.github.com&gt;; 抄送:&nbsp;"徐冰"<1097465337@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [koehlp/wda_tracker] How to visualize multi camera tracks? (#2) Hey SaraXuBing, The DukeMTMC dataset has been removed due to privacy issues (https://www.dukechronicle.com/article/2019/06/duke-university-facial-recognition-data-set-study-surveillance-video-students-china-uyghur). This was a reason why we created the MTA dataset. You cannot publish research based on the DukeMTMC I guess. Best regards, Philipp — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hi Sara,

How is your research going?
I am also doing research in MTMC, can we make some communications and exchange status?

BRs,
Charles
